### ISSUE TITLE
API Update to Show Team Information

### ISSUE THREAD

**Issue by HanDamilton** [DonorDrive/PublicAPI#20]
Hello,

I'm slightly a beginner to coding and I'm not sure if this constitutes and issue, but figured I'd ask.

I'm trying to modify the Extra Life overlay which is using the DonorDrive API to view team information as opposed to it's current setup to only show single participant info.

Example URL they are using: 
https://www.extra-life.org/index.cfm?fuseaction=donorDrive.streamingOverlay&eventID=543&participantID=375493&preview=true

I went into the HTML file and subbed in "participant" and the appropriate ID with "team" as well as that appropriate ID.

While this led the code to resolve it did not actually update the visual graphics. Finding this github I went through and tried to ensure the calls for Team information outlined here were in place in the HTML which they seemed to be, but it's still not pulling. 

Any suggestions? 

[ELDonorDrive_Teams_v0.txt](https://github.com/DonorDrive/PublicAPI/files/3735476/ELDonorDrive_Teams_v0.txt)

**Comment by timmixell** [comment]
@HanDamilton , 

The overlay doesn't currently support teams. It's definitely something we're considering, but for now, you would need to roll your own using the Teams endpoints in the API.

If you're running the overlay locally, you need to make sure to update the domain to extra-life.org. Otherwise, it will try running from localhost. You can see network calls in your browser's dev console.

Hope this helps,
Tim
